INSERT INTO burgers (burger) VALUES ('Hamburger');
INSERT INTO burgers (burger) VALUES ('Cheeseburger');
INSERT INTO burgers (burger) VALUES ('Double Cheese Hamburger');
INSERT INTO burgers (burger) VALUES ('Chicken Sandwich');
INSERT INTO burgers (burger) VALUES ('Classic Cheese Burger');
INSERT INTO burgers (burger) VALUES ('Regular Hamburger');
INSERT INTO burgers (burger) VALUES ('Bacon Cheeseburger');
INSERT INTO burgers (burger) VALUES ('Double Cheese Bacon Hamburger');
INSERT INTO burgers (burger) VALUES ('Grilled Chicken Sandwich');
INSERT INTO burgers (burger) VALUES ('Classic Cheddar Burger');
INSERT INTO burgers (burger) VALUES ('Double Cheese Bacon Hamburger');
INSERT INTO burgers (burger) VALUES ('Grilled Chicken Sandwich');
INSERT INTO burgers (burger) VALUES ('Classic Cheddar Burger');